<?php

namespace ContainerFMeCFzA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSellerControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\SellerController' shared autowired service.
     *
     * @return \App\Controller\SellerController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/SellerController.php';

        $container->services['App\\Controller\\SellerController'] = $instance = new \App\Controller\SellerController();

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Controller\\SellerController', $container));

        return $instance;
    }
}
