<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXEFj4Re\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXEFj4Re/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXEFj4Re.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXEFj4Re\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXEFj4Re\App_KernelDevDebugContainer([
    'container.build_hash' => 'XEFj4Re',
    'container.build_id' => '7d9f0b2e',
    'container.build_time' => 1606338390,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXEFj4Re');
